language: objective-c
osx_image: xcode8.3
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Alamofire.xcworkspace
  - IOS_FRAMEWORK_SCHEME="Alamofire iOS"
  - MACOS_FRAMEWORK_SCHEME="Alamofire macOS"
  - TVOS_FRAMEWORK_SCHEME="Alamofire tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="Alamofire watchOS"
  - EXAMPLE_SCHEME="iOS Example"
  matrix:

    - DESTINATION="OS=10.3.1,name=iPhone 7"     SCHEME="$IOS_FRAMEWORK_SCHEME"      RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - dh -h
  
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi
